CREATE TABLE public.identity_map (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    entity_type TEXT NOT NULL CHECK (
        entity_type IN ('product_user', 'workspace')
    ),

    product_id TEXT NOT NULL,

    hubspot_object_type TEXT NOT NULL CHECK (
        hubspot_object_type IN ('contact', 'company')
    ),

    hubspot_record_id TEXT NOT NULL,

    resolution_method TEXT NOT NULL CHECK (
        resolution_method IN (
            'stable_id',
            'email_match',
            'domain_match',
            'created_new'
        )
    ),

    resolution_status TEXT NOT NULL DEFAULT 'resolved' CHECK (
        resolution_status IN (
            'resolved',
            'ambiguous',
            'invalidated'
        )
    ),

    resolved_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    last_verified_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT identity_map_product_identity_unique
        UNIQUE (entity_type, product_id),

    CONSTRAINT identity_map_crm_identity_unique
        UNIQUE (hubspot_object_type, hubspot_record_id)
);

CREATE INDEX idx_identity_map_product_id
    ON public.identity_map (product_id);

CREATE INDEX idx_identity_map_hubspot_record
    ON public.identity_map (hubspot_record_id);
