CREATE TABLE public.processing_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    event_id TEXT NOT NULL
        REFERENCES public.product_events(event_id)
        ON DELETE RESTRICT,

    attempt_number INTEGER NOT NULL
        CHECK (attempt_number >= 1),

    processing_status TEXT NOT NULL CHECK (
        processing_status IN (
            'received',
            'validated',
            'processing',
            'completed',
            'rejected',
            'failed',
            'retry_pending',
            'review_required'
        )
    ),

    hubspot_contact_id TEXT,

    hubspot_company_id TEXT,

    qualification_state TEXT,

    handoff_status TEXT,

    failure_type TEXT,

    failure_reason TEXT,

    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    completed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT processing_attempt_unique
        UNIQUE (event_id, attempt_number)
);

CREATE INDEX idx_processing_attempts_event
    ON public.processing_attempts (event_id);

CREATE INDEX idx_processing_attempts_status
    ON public.processing_attempts (processing_status);
