CREATE TABLE public.ingress_rejections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    event_id TEXT,

    event_type TEXT,

    product_user_id TEXT,

    workspace_id TEXT,

    rejection_reason TEXT NOT NULL,

    validation_errors JSONB NOT NULL DEFAULT '[]'::jsonb,

    rejected_payload JSONB NOT NULL,

    rejected_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT validation_errors_must_be_array
        CHECK (jsonb_typeof(validation_errors) = 'array'),

    CONSTRAINT rejected_payload_must_be_object
        CHECK (jsonb_typeof(rejected_payload) = 'object')
);

CREATE INDEX idx_ingress_rejections_event_id
    ON public.ingress_rejections (event_id);

CREATE INDEX idx_ingress_rejections_rejected_at
    ON public.ingress_rejections (rejected_at DESC);

ALTER TABLE public.ingress_rejections
ENABLE ROW LEVEL SECURITY;

REVOKE ALL PRIVILEGES
ON TABLE public.ingress_rejections
FROM anon, authenticated;
